version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform jq
      - terraform init

  build:
    commands:
      - python3 aws-cfn-helper-script.py $destroy
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
